### ISSUE TITLE
Cutting a release to allow use of polling 2.6.0

### ISSUE THREAD

**Issue by erickt** [smol-rs/async-io#117]
Polling 2.6.0 depends on windows-sys 0.45.0, but async-io 1.12.0 depends on windows-sys 0.42.0. Would it be possible to make a new release of async-io, which has already migrated from windows-sys to rustix? That would let us use async-io on some of the new platforms supported by `polling`.

**Comment by notgull** [comment]
Released v1.13.0 with `windows-sys` replaced with `rustix`
