### ISSUE TITLE
[Question]: Why Registration does not contain a `BorrowedFd` instead of a `RawFd`?

### ISSUE THREAD

**Issue by Tudyx** [smol-rs/async-io#178]
When looking at the ` Registration` type for unix ,  I stumbled across the required invariant:

>   This describes a valid file descriptor that has not been `close`d. It will not be closed while this object is alive.

and it looks a lot to what is guarantee by the [BorrowedFd](https://doc.rust-lang.org/stable/std/os/fd/struct.BorrowedFd.html) type:

> This has a lifetime parameter to tie it to the lifetime of something that owns the file descriptor. For the duration of that lifetime, it is guaranteed that nobody will close the file descriptor.

So, I thought naively this is maybe a valid design that will avoid the unsafe and ensure the invariant is respected:

```rust
pub struct Registration<'fd> {
    fd: BorrowedFd<'fd>,
}
```

But I'm sure you are well aware about [BorrowdFd](https://doc.rust-lang.org/stable/std/os/fd/struct.BorrowedFd.html), so my question is, why have you decided to use a `RawFd` and unsafe instead of a `BorrowedFd`?

**Comment by notgull** [comment]
It would add lifetime complications to the API that don't really need to be there.

To clarify, adding this would mean that all `Async` types would need a lifetime parameter, and would need to implicitly operate on only references. As this would make `Async` functionally impossible to use outside of very niche circumstances I haven't done this.

This is essentially equivalent to borrowing the source in place, which is safe in current Rust. The `unsafe` is unfortunate but also probably unavoidable.
