### ISSUE TITLE
Async::<TcpStream>::connect fails on windows

### ISSUE THREAD

**Issue by gzmorell** [smol-rs/async-io#182]
connect fails on windows with "Either the application has not called WSAStartup, or WSAStartup failed."

According to "https://docs.rs/rustix/0.38.30/x86_64-pc-windows-msvc/rustix/net/fn.wsa_startup.html"
pub fn wsa_startup() -> Result<WSADATA>
"On Windows, it’s necessary to initialize the sockets subsystem before using sockets APIs. The function performs the necessary initialization."
Calling this function before trying to connect solves the problem.

**Comment by notgull** [comment]
Ah right. With `rustix`'s socket functions you need to call `wsa_startup` manually.

This can be fixed by either calling that function or by creating and destroying a `TcpStream`.

**Comment by gzmorell** [comment]
But rustix function is not in the api of async-io, so I think it should be called internally. Not by the user of the library. This problem affects smol, as you cannot connect to a socket on windows. This example in smol crate fails to run on windows:
https://github.com/smol-rs/smol/blob/master/examples/tcp-client.rs

**Comment by notgull** [comment]
Yes. I'll accept a PR that creates a network socket internally in order to set up networking. If not I'll file one later.

**Comment by gzmorell** [comment]
As far as I understand this: ""On Windows, it’s necessary to initialize the sockets subsystem before using sockets APIs" means that at least the function should be called once. So it can be called only once. I have no idea what can happen if it is called more than once.
Should a kind of lazy static initialization a bad idea?
