### ISSUE TITLE
Cirrus CI run is failing with a 404 error

### ISSUE THREAD

**Issue by notgull** [smol-rs/async-io#193]
https://github.com/smol-rs/async-io/pull/192/checks?check_run_id=25684946336

@taiki-e I'm not familiar with Cirrus CI, do you know why this is happening?

**Comment by taiki-e** [comment]
The actual error message is:

> "message": **"The resource 'projects/freebsd-org-cloud-dev/global/images/family/freebsd-13-2' was not found"**,

I think the action needed here is the same as https://github.com/smol-rs/polling/pull/206#issuecomment-2143462931:

> The CI failure will probably be fixed by increasing the FreeBSD version to 13.3.
