### ISSUE TITLE
support tokio reactor

### ISSUE THREAD

**Issue by dvc94ch** [smol-rs/async-io#70]
I am very fond of async-io and use it in many projects. However tokio users aren't very happy with the additional thread. Is there any way that we can wrap the tokio evented trait or whatever it's called these days and add a tokio feature flag?

**Comment by taiki-e** [comment]
- IIRC tokio currently provides APIs that might make this possible only on unix. ([AsyncFd](https://docs.rs/tokio/1.10.0/tokio/io/unix/struct.AsyncFd.html))

- How do you handle the differences in approaches to starting reactors? (explicit vs. implicit. If you stick to the implicit, you need a global reactor.)

- Given [how feature flags work](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification), the "switch reactors by feature flags" approach is incorrect. The "feature flags enable both reactors" approach is similar to what async-compat does, and it is inefficient. AFAIK to do this correctly, it requires an approach that uses explicit constructors such as new_with_tokio.

**Comment by dvc94ch** [comment]
> it requires an approach that uses explicit constructors such as new_with_tokio

I guess that would work and would require less work to support tokio than other approaches. Even nicer might be taking an `Option<dyn Reactor>`, so you can just do `Async::new(config.reactor.clone(), ...)`.

**Comment by taiki-e** [comment]
I think this is better suited to be experimented with as a separate crate, so I'll close this one for now.
