### ISSUE TITLE
Fix panic in `Timer` with large durations

### ISSUE THREAD

**Issue by notgull** [smol-rs/async-io#86]
See async-rs/async-std#1037. We should probably use `checked_add` when calculating the instant instead of regular addition.

**Comment by taiki-e** [comment]
["waiting indefinitely"](https://github.com/crossbeam-rs/crossbeam/issues/795#issuecomment-1069514998) or ["waiting a few decades"](https://github.com/tokio-rs/tokio/blob/fc4deaa1d0e35d3404d1d32ddcb4b083081355c0/tokio/src/time/instant.rs#L57-L63) are both reasonable solutions.
